[build]
  command = "npm run build"  # Command to build the project
  publish = "client/dist"    # Directory where the build output is located

[build.environment]
  NODE_VERSION = "16"      # Optional: specify the Node.js version

# Optional: redirects if needed
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
